version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - app-network

  nifi:
    image: apache/nifi:latest
    ports:
      - "9443:9443"
    volumes:
      - ./data:/data  # Sample.csv 경로
    environment:
      - NIFI_WEB_HTTPS_PORT=9443
    networks:
      - app-network

  timescaledb:
    image: timescale/timescaledb:latest-pg12
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    networks:
      - app-network

  superset:
    image: apache/superset:latest-dev
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_LOAD_EXAMPLES: "yes"
      SUPERSET_SECRET_KEY: "a_random_secret_key"
      SQLALCHEMY_DATABASE_URI: postgresql://myuser:mypassword@timescaledb:5432/mydb
    depends_on:
      - timescaledb
    command: >
      /bin/bash -c "
        superset db upgrade &&
        superset init &&
        superset run -h 0.0.0.0 -p 8088
      "
    volumes:
      - superset_home:/app/superset_home
    networks:
      - app-network

volumes:
  timescaledb_data:
  superset_home:

networks:
  app-network:
    driver: bridge
